### ISSUE TITLE
Issue with demo.py

### ISSUE THREAD

**Issue by KristianDukov** [lxy5513/cvToolBox#2]
```
Traceback (most recent call last):
  File "demo.py", line 408, in <module>
    light_track_camera(pose_estimator, video_capture)
  File "demo.py", line 111, in light_track_camera
    human_candidates = get_human_bbox(cur_img, yolo_model)
  File "demo.py", line 57, in get_human_bbox
    bboxs, probs = inference(image, model)
  File "C:\Pytorch\cvToolkit\pose_track\lighttrack\human_detector.py", line 137, in inference
    im_dim_list = torch.index_select(im_dim_list, 0, output[:,0].long())
TypeError: 'NoneType' object is not subscriptable
```

When trying to run it on a video

**Comment by lxy5513** [comment]
` bboxs, probs = inference(image, model)` 
try to print the image, I guess the image is None.
